### ISSUE TITLE
Add support for Fennec nightly

### ISSUE THREAD

**Issue by Natim** [mozilla-services/buildhub#69] opened 2017-05-31 06:59 UTC
https://archive.mozilla.org/pub/mobile/nightly/2017/05/2017-05-30-10-01-27-mozilla-central-android-api-15-old-id/fennec-55.0a1.multi.android-arm.apk

The generation of a unique ID for this URL is not unique.

It set the following ID: ``fennec_2017-05-30-10-01-27_55-0a1_android-arm_multi`` while it should set ``fennec_2017-05-30-10-01-27_55-0a1_android-arm_multi``

We have other example of another URL that returns the exact same ID, leading to missing builds:

- https://archive.mozilla.org/pub/mobile/nightly/2017/05/2017-05-30-10-01-27-mozilla-central-android-x86-old-id/fennec-55.0a1.multi.android-i386.apk

The latter should set: ``fennec_2017-05-30-10-01-27_55-0a1_android-i386_multi``

**Comment by Natim** [comment] 2017-05-31 07:20
Should it be ``fennec_2017-05-30-10-01-27_55-0a1_android-arm_multi`` or ``fennec_2017-05-30-10-01-27_55-0a1_android-api-15_multi``?

**Comment by leplatrem** [comment] 2017-05-31 09:12
It could also be `fennec_2017-05-30-10-01-27_55-0a1_android-api-15-old-id_multi`

**Comment by Natim** [comment] 2017-05-31 09:14
What is this old-id thing?

**Comment by leplatrem** [comment] 2017-05-31 09:15
> What is this old-id thing?

no id 🥁

**Comment by Natim** [comment] 2017-05-31 09:24
> > What are the difference between:
>> - https://archive.mozilla.org/pub/mobile/nightly/2017/05/2017-05-30-10-01-27-mozilla-central-android-api-15/fennec-55.0a1.multi.android-arm.apk
>> and
>> - https://archive.mozilla.org/pub/mobile/nightly/2017/05/2017-05-30-10-01-27-mozilla-central-android-api-15-old-id/fennec-55.0a1.multi.android-arm.apk
>> What is the ``old-id`` thing?
>
> I have no idea 🥁

Maybe @willkg or @pocmo know about the difference between both and if both build are useful.

**Comment by pocmo** [comment] 2017-05-31 09:33
This is an artifact from "Project Dawn" (Aurora builds going away). Nightly used to be org.mozilla.fennec (Android package name) and was updated via our own updater. Aurora was published to Google Play and used org.mozilla.fennec_aurora as package id. Now Aurora is going away but we want to keep our builds and users on Google Play (10x the usage number than our Nightly builds) so we re-branded it to be Nightly - but we need to keep the package name (It can never change). So now we are distributing Nightly on Google Play with package id org.mozilla.fennec_aurora. We still build Nightly with the old id (org.mozilla.fennec) until we have convinced most users to switch to the new build.

**Comment by Natim** [comment] 2017-05-31 09:39
That's actually a really useful information. So on our end we need to handle both as different builds. Makes a lot of sense thanks.

**Comment by leplatrem** [comment] 2017-05-31 14:41
Duplicate of #44 ?

**Comment by Natim** [comment] 2017-05-31 14:47
For the arch part yes but not for URL part I don't think it is a duplicate.

**Comment by leplatrem** [comment] 2017-08-02 15:45
I believe we're good now.

https://mozilla-services.github.io/buildhub/searchkit/?channel[0]=nightly-old-id&channel[1]=nightly&products[0]=fennec

**Closed by leplatrem** 2017-08-02 15:45 UTC
Labels: aggregator
